excluded:
  - Pods

disabled_rules:
- trailing_whitespace
- identifier_name
- type_body_length
- function_parameter_count
- cyclomatic_complexity
- vertical_whitespace

force_cast: warning

line_length:
    warning: 150
    error: 200

file_length:
    warning: 650
    error: 1000

type_name:
    min_length: 2
    max_length: 40

function_body_length:
    warning: 80
    error: 100

nesting:
    type_level:
    warning: 3
    error: 5
    statement_level:
    warning: 4
    error: 6
    
todo: # TODO, FIXME 미해결 확인
    included: ".*.swift"
    match_kinds: comment
    severity: warning
    
mark: # MARK 유효 형식 체크
    included: ".*.swift"
    match_kinds: comment
    severity: error
