excluded:
  - Pods

disabled_rules:
- trailing_whitespace
- identifier_name
- type_body_length
- function_parameter_count
- cyclomatic_complexity
- vertical_whitespace
- comma
- multiple_closures_with_trailing_closure
- comment_spacing
- orphaned_doc_comment

force_cast: warning

large_tuple:
    warning: 3
    error: 5
    
line_length:
    warning: 160
    error: 200

file_length:
    warning: 600
    error: 700

type_name:
    min_length: 2
    max_length: 40

function_body_length:
    warning: 80
    error: 100

nesting:
    type_level:
    warning: 3
    error: 5
    statement_level:
    warning: 4
    error: 6
    
todo: # TODO, FIXME 미해결 확인
    included: ".*.swift"
    match_kinds: comment
    severity: warning
    
mark: # MARK 유효 형식 체크
    included: ".*.swift"
    match_kinds: comment
    severity: error
